"""
llm_engine.py
-------------
Wraps all calls to the Google Gemini API (free tier) for RAG-based question
answering, summarization, keyword extraction, citation analysis, research
gap identification, and future work suggestions.
"""

import os
from pathlib import Path
from dotenv import load_dotenv
import google.generativeai as genai

# Load .env from backend directory, project root, and current working directory
backend_dir = Path(__file__).resolve().parent
load_dotenv(backend_dir / ".env")
load_dotenv(backend_dir.parent / ".env")
load_dotenv()


def _get_api_key():
    key = (
        os.environ.get("GEMINI_API_KEY")
        or os.environ.get("GOOGLE_API_KEY")
        or os.environ.get("GEMINI_KEY")
        or os.environ.get("API_KEY")
    )
    if key:
        return key.strip().strip('"').strip("'")
    return None


def _get_model():
    api_key = _get_api_key()
    if not api_key:
        raise ValueError(
            "GEMINI_API_KEY not found. Please add GEMINI_API_KEY=your_key to backend/.env and restart the backend server."
        )
    genai.configure(api_key=api_key)
    model_name = os.environ.get("GEMINI_MODEL", "gemini-3.6-flash")
    return genai.GenerativeModel(model_name)


def _ask_gemini(system_prompt: str, user_prompt: str) -> str:
    full_prompt = f"{system_prompt}\n\n{user_prompt}"
    try:
        model = _get_model()
        response = model.generate_content(full_prompt)
        if response and hasattr(response, "text") and response.text:
            return response.text
        return "No response generated by model."
    except Exception as e:
        err_msg = str(e)
        print(f"[Gemini API Error] {err_msg}")
        if not _get_api_key():
            return "Please set your GEMINI_API_KEY in backend/.env and restart the backend server."
        # Try fallback to gemini-2.0-flash if model name was unsupported
        try:
            fallback_model = genai.GenerativeModel("gemini-3.6-flash")
            response = fallback_model.generate_content(full_prompt)
            if response and hasattr(response, "text") and response.text:
                return response.text
        except Exception as fallback_err:
            return f"Gemini API Error: {str(fallback_err)}"
        return f"Gemini API Error: {err_msg}"


def answer_question(question: str, retrieved_chunks: list[str]) -> str:
    """Stage-2 RAG: generate a context-grounded answer from retrieved chunks."""
    context = "\n\n---\n\n".join(retrieved_chunks)
    system_prompt = (
        "You are a research assistant. Answer the user's question using ONLY the "
        "provided context from the research paper. If the answer is not in the "
        "context, say so clearly instead of guessing."
    )
    user_prompt = f"Context from the paper:\n{context}\n\nQuestion: {question}"
    return _ask_gemini(system_prompt, user_prompt)

def summarize_document(full_text_sample: str) -> str:
    system_prompt = (
        "You are a research assistant that writes concise, accurate summaries "
        "of academic papers for students and researchers."
    )
    user_prompt = f"Summarize the following research paper content in 150-200 words:\n\n{full_text_sample}"
    return _ask_gemini(system_prompt, user_prompt)


def extract_keywords(full_text_sample: str) -> str:
    system_prompt = (
        "You extract the most important technical keywords and key concepts "
        "from academic text. Return them as a comma-separated list only."
    )
    user_prompt = f"Extract 10-15 key terms from this text:\n\n{full_text_sample}"
    return _ask_gemini(system_prompt, user_prompt)


def analyze_citations(full_text_sample: str) -> str:
    system_prompt = (
        "You identify and summarize how a paper's citations/references are used, "
        "and what related work is mentioned, based on the visible text."
    )
    user_prompt = f"Analyze the citations and related work mentioned in this text:\n\n{full_text_sample}"
    return _ask_gemini(system_prompt, user_prompt)


def identify_research_gaps(full_text_sample: str) -> str:
    system_prompt = (
        "You are an expert reviewer who identifies unresolved problems, "
        "limitations, and open research gaps implied by a paper's content."
    )
    user_prompt = f"Identify potential research gaps in this paper:\n\n{full_text_sample}"
    return _ask_gemini(system_prompt, user_prompt)


def suggest_future_work(full_text_sample: str) -> str:
    system_prompt = (
        "You suggest concrete, actionable future research directions that "
        "naturally follow from a paper's content and limitations."
    )
    user_prompt = f"Suggest 4-6 future work directions based on this paper:\n\n{full_text_sample}"
    return _ask_gemini(system_prompt, user_prompt)


def generate_flashcards(full_text_sample: str) -> str:
    system_prompt = (
        "You are an expert tutor. Extract 5-10 key concepts from the text and create flashcards. "
        "Return ONLY a valid JSON array of objects, with no markdown formatting. "
        'Each object must have "question" and "answer" string properties.'
    )
    user_prompt = f"Create flashcards for this text:\n\n{full_text_sample}"
    return _ask_gemini(system_prompt, user_prompt)


def generate_glossary(full_text_sample: str) -> str:
    system_prompt = (
        "You are a technical editor. Extract 10-15 complex terms or acronyms from the text and define them. "
        "Return ONLY a valid JSON array of objects, with no markdown formatting. "
        'Each object must have "term" and "definition" string properties.'
    )
    user_prompt = f"Create a glossary for this text:\n\n{full_text_sample}"
    return _ask_gemini(system_prompt, user_prompt)


def extract_title(full_text_sample: str) -> str:
    system_prompt = (
        "Extract the main title of this research paper based on the text. "
        "Return ONLY the title string, nothing else. Do not wrap in quotes."
    )
    user_prompt = f"Text:\n\n{full_text_sample}"
    return _ask_gemini(system_prompt, user_prompt)


def generate_concept_tree(full_text_sample: str) -> str:
    system_prompt = (
        "You are a data structurer. Create a hierarchical concept tree representing the core structure of this paper. "
        "Return ONLY a valid JSON object, with no markdown formatting. "
        'The JSON MUST have a root "name" (e.g., the paper topic), and a "children" array of objects. '
        'Each child can have a "name" and its own "children" array, up to 3 levels deep.'
    )
    user_prompt = f"Create a concept tree for this text:\n\n{full_text_sample}"
    return _ask_gemini(system_prompt, user_prompt)
